version: '3.1'
services:
  db:
    image: mysql:8.0.19
    container_name: mysql_agendamentoemail
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root